<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PMPS" Id="{3b7307dd-d4f5-405e-8e38-9780f4bf414e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PMPS
VAR
	fbArbiterIO : FB_SubSysToArbiter_IO;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbArbiterIO(Arbiter := GVL_PMPS.g_fbArbiter1, fbFFHWO := GVL_PMPS.g_FastFaultOutput1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>