<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_1_PlcTask" Id="{6c74c1b3-089b-4af5-bdef-e72814f71ef8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_1_PlcTask
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_MR1L0_HOMS();
PRG_MR2L0_HOMS();
PRG_PMPS();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>