IOC_TOP = /reg/g/pcds/epics/R7.0.2-2.0/ioc/ads-ioc/v0.1.5
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = MR1L0-MR2L0
PROJECT_PATH := ../../MR1L0-MR2L0/MR1L0-MR2L0.tsproj
PLC = MR1L0_MR2L0_PLC

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
